CREATE TABLE [dbo].[LookUp]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Category] VARCHAR (150) NOT NULL,
	[Name] VARCHAR (200) NOT NULL,
	
)
GO

ALTER TABLE [dbo].[LookUp] ADD CONSTRAINT [PK_Lookup] PRIMARY KEY CLUSTERED  ([Id])
GO