CREATE TABLE [dbo].[Flat]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[RoomNumber] UNIQUEIDENTIFIER  NOT NULL,
	[TotalFlats] UNIQUEIDENTIFIER  NOT NULL,
    [CreatedBy] UNIQUEIDENTIFIER  NOT NULL,
	[UpdatedBy] UNIQUEIDENTIFIER NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[UpdatedDate] DATETIME NOT NULL,
	
)
GO

ALTER TABLE [dbo].[Flat] ADD CONSTRAINT [PK_Flat] PRIMARY KEY CLUSTERED  ([Id])

GO