CREATE TABLE [dbo].[Payment]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[TransactionId] UNIQUEIDENTIFIER  NOT NULL,
	[BookingId] UNIQUEIDENTIFIER  NOT NULL,
	[Amount] DECIMAL  NOT NULL,
    [CreatedBy] UNIQUEIDENTIFIER  NOT NULL,
	[UpdatedBy] UNIQUEIDENTIFIER NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[UpdatedDate] DATETIME NOT NULL,
	
)
GO

ALTER TABLE [dbo].[Payment] ADD CONSTRAINT [PK_Payment] PRIMARY KEY CLUSTERED  ([Id])

GO