CREATE TABLE [dbo].[Booking]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[BookingRequestId] UNIQUEIDENTIFIER  NOT NULL,
	[Flat] UNIQUEIDENTIFIER  NOT NULL,
	[Status] UNIQUEIDENTIFIER  NOT NULL,
    [CreatedBy] UNIQUEIDENTIFIER  NOT NULL,
	[UpdatedBy] UNIQUEIDENTIFIER NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[UpdatedDate] DATETIME NOT NULL,
	
)
GO

ALTER TABLE [dbo].[Booking] ADD CONSTRAINT [PK_Booking] PRIMARY KEY CLUSTERED  ([Id])

GO