CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] VARCHAR (100) NOT NULL,
	[Email] VARCHAR (150) NOT NULL,
	[CreatedById] UNIQUEIDENTIFIER NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[UpdatedById] UNIQUEIDENTIFIER NOT NULL,
	[UpdatedDate] DATETIME NOT NULL
)
GO

ALTER TABLE [dbo].[User] ADD CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED  ([Id])
GO